### ISSUE TITLE
IMG_7737.PNGで例外発生

### ISSUE THREAD

**Issue by fgophi** [max747/fgojunks#1]
pageinfo.py の実行時、[IMG_7737.PNG](https://github.com/fgophi/scrennshots4debug/blob/master/pageinfo/IMG_7737.PNG)で例外が発生します

以下実行結果です

  $ pageinfo.py IMG_7737.PNG

  Traceback (most recent call last):
    File "pageinfo.py", line 347, in
   <module>
      main(args)
    File "pageinfo.py", line 303, in
   main
      result = look_into_file(filename, args)
    File "pageinfo.py", line 288, in
   look_into_file
      pagenum, pages, lines = guess_pageinfo(im, args.debug_sc, debug_sc_image)
    File "pageinfo.py", line 254, in
   guess_pageinfo
      scrollable_area_region = scrollable_area_contours[0]
  IndexError: list index out of range

**Comment by max747** [comment]
このようにスクロールバーを誤検出し、一方でスクロール可能領域は検出しないためにプログラムが想定しないケースとなり IndexError が生じています。

![IMG_7737](https://user-images.githubusercontent.com/696577/81309244-b1893780-90bd-11ea-8ef1-d5ef48fc5117.PNG)


スクロール可能領域が検出できない場合は、その前に検出したスクロールバーは誤検出であるとみなし、スクロールバーなしとして扱うようにします。

**Comment by max747** [comment]
61ed41d3 で修正。
4e139ae6 でテストケースに追加済。

**Comment by max747** [comment]
テスト通ってますので close します。問題があれば reopen してください。
