### ISSUE TITLE
pageinfo.py がJPEG化したファイルで誤認識

### ISSUE THREAD

**Issue by fgophi** [max747/fgojunks#2]
fgosccnt でJPEG対応を試みているのですが、lineinfo.py での問題があるのでご報告

- IMG_0872.PNG をJPEG化したIMG_0872_R.PNG
- IMG_0901.PNG をJPEG化したIMG_0901_R.PNG

が正しい情報を返しませんでした
```
$ pageinfo.py  IMG_0872.PNG
IMG_0872.PNG,2,2,4

$ pageinfo.py  IMG_0872_R.JPG
IMG_0872_R.JPG,1,1,3

$ pageinfo.py  IMG_0901.PNG
IMG_0901.PNG,2,2,4

$ pageinfo.py  IMG_0901_R.JPG
IMG_0901_R.JPG,1,1,3

```

![IMG_0872](https://user-images.githubusercontent.com/62515228/87268772-40735f80-c506-11ea-91a2-994894543727.PNG)
![IMG_0872_R](https://user-images.githubusercontent.com/62515228/87268796-4e28e500-c506-11ea-9c3d-3f7a4d4a04f2.JPG)
![IMG_0901](https://user-images.githubusercontent.com/62515228/87269062-0d7d9b80-c507-11ea-9fa2-7d262452318f.PNG)
![IMG_0901_R](https://user-images.githubusercontent.com/62515228/87269094-1f5f3e80-c507-11ea-9f5b-aaad9be64cce.JPG)

**Comment by max747** [comment]
jpeg の場合にスクロール可能領域を検出できていないようです。
閾値の調整で解決するか試します。調整だけでうまくいかない場合は画像形式をオプションで渡してもらうよう関数の引数を増やす必要があるかもしれません。

## png
<img src="https://user-images.githubusercontent.com/696577/87272281-b54b9700-c510-11ea-8039-3faa587a8f0d.png" height="512">

## jpeg

<img src="https://user-images.githubusercontent.com/696577/87272284-b8468780-c510-11ea-838c-54293e066d50.jpg" height="512">

**Comment by fgophi** [comment]
画像形式はすでに内部で渡しているので渡すのは容易です
